### ISSUE TITLE
dark mode support

### ISSUE THREAD

**Issue by jezzzm** [polemius/recoil-logger#1]
Hi @polemius , would be cool if this tool had dark mode-friendly colours. Currently a struggle to read console output unless I switch to light mode.

Mind if I open a PR to support dark?

Cheers!

**Comment by polemius** [comment]
Hi @jezzzm, very good point. Sure, go ahead and open PR 👍

**Comment by polemius** [comment]
@huy-lv Hi, this package support the light and dark modes but the system ones. We are checking the theme mode by `window.matchMedia('(prefers-color-scheme: dark)')` and if it is match then we are assuming that user has a dark theme.

Do you have in system preference the dark mode turn on? and the devtools has the light mode from devtools settings?

I have tried find out how I can check the devtools' theme and looks like we couldn't have this information from JavaScript.

**Comment by huy-lv** [comment]
haha exactly dev tool is in light theme and system is in dark theme. Everything will be okay if you chang text color to gray or something like that, so we can see it in both themes
